// <auto-generated />
using System;
using Local_Alternatives.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Local_Alternatives.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241019080954_CityModelAndSeeder")]
    partial class CityModelAndSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Local_Alternatives.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Local_Alternatives.Models.Cities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef649b44-173f-450c-a469-dd67ea1ec4ae"),
                            Country = "North Macedonia",
                            Name = "Skopje",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("fd43a4c7-30b5-417d-930e-51de641ec69c"),
                            Country = "North Macedonia",
                            Name = "Kumanovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("74430888-fb99-4084-81e0-0a8dd34bb63a"),
                            Country = "North Macedonia",
                            Name = "Bitola",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("78c5c972-7281-4d57-aee2-90c51e0e594d"),
                            Country = "North Macedonia",
                            Name = "Prilep",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("fa7e44d6-fc9f-48fc-84c7-c6a08243e927"),
                            Country = "North Macedonia",
                            Name = "Tetovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("e16e12b0-a266-45fc-bf66-b024dd0316d0"),
                            Country = "North Macedonia",
                            Name = "Štip",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("aefc1c66-aae8-499a-928f-78fc5ec72a75"),
                            Country = "North Macedonia",
                            Name = "Veles",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("d8616eb7-e68f-42c8-aa6f-c22f84a3697f"),
                            Country = "North Macedonia",
                            Name = "Ohrid",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("fd0e6f7f-e395-4c31-b4e7-0d72564e2a97"),
                            Country = "North Macedonia",
                            Name = "Strumica",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("afce181a-e86f-4676-9cd8-c419b61c19be"),
                            Country = "North Macedonia",
                            Name = "Gostivar",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("b3b2dae5-ebc4-4f09-b04c-13a3e3f23c70"),
                            Country = "North Macedonia",
                            Name = "Kočani",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("f194df50-539e-4c94-add0-a47f416a429e"),
                            Country = "North Macedonia",
                            Name = "Dračevo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("2daa1cd1-7b7f-4117-b536-d6354deb6323"),
                            Country = "North Macedonia",
                            Name = "Struga",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("9ba57083-de70-4f6e-ab42-64819ab2f48e"),
                            Country = "North Macedonia",
                            Name = "Debar",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("f6392c82-e8b6-4716-8cfd-a7cdd21401f0"),
                            Country = "North Macedonia",
                            Name = "Kriva Palanka",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("45bca370-7f3e-4558-8e95-01c587dd162f"),
                            Country = "North Macedonia",
                            Name = "Negotino",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("7f72204c-12e3-4dd8-9905-3448b5febede"),
                            Country = "North Macedonia",
                            Name = "Sveti Nikole",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("1e00175d-5895-4a23-ba7c-66bba2896945"),
                            Country = "North Macedonia",
                            Name = "Probištip",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("c3cd95a0-d19a-4b23-a0f5-1129af5cd6a1"),
                            Country = "North Macedonia",
                            Name = "Delčevo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("7dcfbb59-bbe7-4b00-b447-babdb67abbd6"),
                            Country = "North Macedonia",
                            Name = "Vinica",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("2e6609cc-175b-402c-92ca-3e6f1e6c46d6"),
                            Country = "North Macedonia",
                            Name = "Aračinovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("1df573ff-f90e-49c0-b5e4-0d4dc2852602"),
                            Country = "North Macedonia",
                            Name = "Kičevo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("d5d8b778-7440-40f2-bf62-ba5e781a1c34"),
                            Country = "North Macedonia",
                            Name = "Kavadarci",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("c214be37-25ed-471d-8e5f-3bf6f04abee4"),
                            Country = "North Macedonia",
                            Name = "Berovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("bb5782a2-3848-498e-ba76-61d8f2b1b0b8"),
                            Country = "North Macedonia",
                            Name = "Kratovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("d4447a29-7efa-4fa5-9f92-9b775f2f794b"),
                            Country = "North Macedonia",
                            Name = "Gevgelija",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("51caef44-9e0c-438b-8ea6-aab3064eb9b2"),
                            Country = "North Macedonia",
                            Name = "Vrapčište",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("644ac88a-4cbb-4247-8c89-c695c3c0a8c6"),
                            Country = "North Macedonia",
                            Name = "Radoviš",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("9b849891-1ad0-42f9-b707-4c381029a63d"),
                            Country = "North Macedonia",
                            Name = "Kruševo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("1fe0cbc3-aaab-4831-8193-e326417e1148"),
                            Country = "North Macedonia",
                            Name = "Čegrane",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("60aebab1-6f79-4815-a1b0-5d95214e6fb2"),
                            Country = "North Macedonia",
                            Name = "Makedonski Brod",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("2a19595a-7cb4-422d-a42d-26606239b092"),
                            Country = "North Macedonia",
                            Name = "Demir Kapija",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("87e574a1-fb00-4da7-973a-deeb77035295"),
                            Country = "North Macedonia",
                            Name = "Kučevište",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("d23c6091-f981-4499-8aaf-39d31612f753"),
                            Country = "North Macedonia",
                            Name = "Tearce",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("661530ee-fb6f-4ae0-8a78-757e53a9d5e9"),
                            Country = "North Macedonia",
                            Name = "Bogdanci",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("1ba0d928-df63-444e-86cf-d1cf059b6c47"),
                            Country = "North Macedonia",
                            Name = "Forino",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("427e07a7-1fae-4d53-9df1-378203702fe8"),
                            Country = "North Macedonia",
                            Name = "Rašče",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("5c81bfde-5a1f-4e81-92aa-897e088c2bc3"),
                            Country = "North Macedonia",
                            Name = "Rosoman",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("c1bac992-7051-4174-9231-a6ebf52ed203"),
                            Country = "North Macedonia",
                            Name = "Demir Hisar",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("968cf7cc-216e-40ed-a3a9-6848b63f8c32"),
                            Country = "North Macedonia",
                            Name = "Vevčani",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("24f2c1e9-b27c-40cf-bd97-f393892084ce"),
                            Country = "North Macedonia",
                            Name = "Gradsko",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("463be817-becc-4b79-a4db-7ca59826e1ee"),
                            Country = "North Macedonia",
                            Name = "Valandovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("cef45d47-f9ef-4d84-a2d0-e520d76b7488"),
                            Country = "North Macedonia",
                            Name = "Krivogaštani",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("3985f289-6e24-4098-a1f7-dbe9171bc851"),
                            Country = "North Macedonia",
                            Name = "Pehčevo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("c883a79b-bc7f-470a-b07b-0cd0c9d5a244"),
                            Country = "North Macedonia",
                            Name = "Plasnica",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("6783123e-1891-4479-a1bd-c6fe09ad41f2"),
                            Country = "North Macedonia",
                            Name = "Zrnovci",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("42ca0f48-ef57-48da-8e0a-14e6960631c2"),
                            Country = "North Macedonia",
                            Name = "Novaci",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("b9b5c873-1c00-4d08-b69b-4ed2d5674315"),
                            Country = "North Macedonia",
                            Name = "Bosilovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("74cb8d50-cd9f-4cb7-9f00-cdb896e0dbcf"),
                            Country = "North Macedonia",
                            Name = "Mogila",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("64b86782-6fe2-4c02-9ad8-5449d341e106"),
                            Country = "North Macedonia",
                            Name = "Novo Selo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("d393ce95-d04e-42c2-b045-a721e5da3116"),
                            Country = "North Macedonia",
                            Name = "Konče",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("a7c4cdb3-9a5d-4344-8e55-98d383096590"),
                            Country = "North Macedonia",
                            Name = "Rostuša",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("010ae911-76cc-4a31-87ef-c819229ee63a"),
                            Country = "North Macedonia",
                            Name = "Jegunovce",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("6aa71a8a-5b3b-4612-a051-ff8f3e77bf64"),
                            Country = "North Macedonia",
                            Name = "Rankovce",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("74f2301d-6d65-4731-975a-1d759a5006d4"),
                            Country = "North Macedonia",
                            Name = "Sopište",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("bcea6451-7a6a-4bb5-90c8-5679999ce523"),
                            Country = "North Macedonia",
                            Name = "Obleševo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("8aa82800-a354-4c21-b83d-2bf12afade88"),
                            Country = "North Macedonia",
                            Name = "Vasilevo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("b7338e89-daea-4670-a66f-0a44f67ce510"),
                            Country = "North Macedonia",
                            Name = "Karbinci",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("bd177857-efd3-4467-9f6e-eeeda6fa90ee"),
                            Country = "North Macedonia",
                            Name = "Lozovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("2dfef260-7d99-46f4-889c-b09cbbac5d58"),
                            Country = "North Macedonia",
                            Name = "Staro Nagoričane",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("0ada7797-e3df-44d8-bbc0-4a2072e9deab"),
                            Country = "North Macedonia",
                            Name = "Brvenica",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("1f7f84f2-6d76-4fbf-b1c4-95cc31102ff4"),
                            Country = "North Macedonia",
                            Name = "Centar Župa",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("082a33af-a382-443a-9f01-4ce63b2fa710"),
                            Country = "North Macedonia",
                            Name = "Dolneni",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("847a3192-0eaa-49d8-a304-18b8224ce530"),
                            Country = "North Macedonia",
                            Name = "Belčišta",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("82016235-d96d-407b-b8e4-c52bf2a9c86a"),
                            Country = "North Macedonia",
                            Name = "Čučer-Sandevo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("8ccd2fc0-f051-4be4-97b8-7a96799287f2"),
                            Country = "North Macedonia",
                            Name = "Zelenikovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("0f42bb35-f91e-48c7-a2d0-cf5ea9440400"),
                            Country = "North Macedonia",
                            Name = "Petrovec",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("869e1af5-2b61-4ceb-828a-6772220cbf6e"),
                            Country = "North Macedonia",
                            Name = "Želino",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("43b2ee40-2bdc-475f-b1d3-b0a65c58383a"),
                            Country = "North Macedonia",
                            Name = "Star Dojran",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("086dffb8-a20d-456b-aee6-c2176114313a"),
                            Country = "North Macedonia",
                            Name = "Studeničani",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("6325ac96-9e7f-4229-b537-3e4ce02e4d8b"),
                            Country = "North Macedonia",
                            Name = "Bogovinje",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("e8645d63-f73f-471e-b93d-a066c8b0ec27"),
                            Country = "North Macedonia",
                            Name = "Ilinden",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("b3fcaadd-dcec-4d07-9f75-7a8c7a19329b"),
                            Country = "North Macedonia",
                            Name = "Lipkovo",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("2844b5a5-936f-4529-8e5a-290667eb7605"),
                            Country = "North Macedonia",
                            Name = "Makedonska Kamenica",
                            PrimaryCity = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("c4caf395-d8b0-4cbc-b482-49086f81784e"),
                            Country = "North Macedonia",
                            Name = "Resen",
                            PrimaryCity = "Unknown"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "909e1479-6647-41b4-a2d4-9609c2f7e7be",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7312d943-52da-4df3-a261-78cee3dcbf25",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Local_Alternatives.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Local_Alternatives.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Local_Alternatives.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Local_Alternatives.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
